config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'subscriptions#index'
  resources :subscriptions
  get 'manage', to: 'pages#manage'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :subscriptions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def manage
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def index
    @subscriptions = current_user.subscriptions
    @subscription = Subscription.new
  end

  def show
    @subscription = Subscription.find(params[:id])
  end

  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.user = current_user
    if @subscription.save
      redirect_to subscriptions_path
    else
      render :new
    end
  end

  def edit
    @subscription = Subscription.find(params[:id])
  end

  def update
    @subscription = Subscription.find(params[:id])
    @subscription.update(subscription_params)
    redirect_to subscription_path(@subscription)
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy
    redirect_to subscriptions_path
  end

  private

  def subscription_params
    params.require(:subscription).permit(:title, :price, :start_date, :billing_frequency)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Subscriptionapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/manage.html.erb
<div class="text-center">
  <h1> Manage Subscriptions</h1>
</div>
<div class="container">

    <div id="amazon prime">
    <div class="subscription-card zoom">
      <div class="subscription-card-info">
        <h2>Amazon Prime</h2>
        <h3 class="card-trip-pricing"> <a href="https://www.amazon prime.com/signup/planform"> Pricing</a><a href="https://www.amazon prime.com/CancelPlan">        Cancel</a></h3>
        <div>
          <img src="https://logo.clearbit.com/<%= "amazon prime".split(' ').first.downcase %>.com" class="card-trip-user">
        </div>
      </div>
    </div>
  </div>

  <div id="audible">
    <div class="subscription-card zoom">
      <div class="subscription-card-info">
        <h2>Audible</h2>
        <h3 class="card-trip-pricing"> <a href="https://www.audible.com/signup/planform"> Pricing</a><a href="https://www.audible.com/CancelPlan">        Cancel</a></h3>
        <div>
          <img src="https://logo.clearbit.com/<%= "Audible".split(' ').first.downcase %>.com" class="card-trip-user">
        </div>
      </div>
    </div>
  </div>
  <div id="netflix">
    <div class="subscription-card zoom">
      <div class="subscription-card-info">
        <h2>Netflix</h2>
        <h3 class="card-trip-pricing"> <a href="https://www.netflix.com/signup/planform"> Pricing</a><a href="https://www.netflix.com/CancelPlan">        Cancel</a></h3>
        <div>
          <img src="https://logo.clearbit.com/<%= "Netflix".split(' ').first.downcase %>.com" class="card-trip-user">
        </div>
      </div>
    </div>
  </div>




</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Manage Subscriptions", manage_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/subscriptions/_audible.html.erb
<a href="https://www.audible.com/signup/planform" target="_blank"> Pricing</a>
<br>
<a href="https://www.audible.com/CancelPlan" target="_blank"> Cancel</a>

app/views/subscriptions/index.html.erb
    <div class="container">
      <div class="section-title"><h5 class='m-0'>My Subscriptions (<%=  @subscriptions.count %>)</h5>
        <button type="button" class="btn add-subscription-btn" data-toggle="modal" data-target="#myModal">Add a Subscription  <i class="fas fa-plus"></i></button>
      </div>
      <div class="subscriptions-table-category-names">
        <div class='service-title'>SERVICE</div>
        <div class='price-title'>PRICE</div>
      </div>
      <div class="subscriptions-holder">
        <% @subscriptions.each do |subscription| %>
          <%= link_to subscription_path(subscription), style: 'text-decoration: none; margin: 0;' do %>
            <div class="subscription-card zoom">
              <div class="subscription-card-info">
                <h2><%= subscription.title.capitalize %></h2>
                <h3 class="card-trip-pricing">$<%= subscription.price %></h3>
                <div>
                  <img src="https://logo.clearbit.com/<%= subscription.title.split(' ').first.downcase %>.com" class="card-trip-user">
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!------- Large modal ---------->


<div class="cards-container">
  <div class="modal fade" id='myModal' tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <div class="modal-title-container">
            <h2>Add Subscription</h2>
            <div>
              <button type="button" class="btn btn-default" data-dismiss="modal" data-target="#myModal"><i class="fas fa-times"></i></button>
            </div>
          </div>
        </div>
        <div class="modal-body">
          <%= simple_form_for Subscription.new do |f| %>
          <%= f.input :title %>
          <%= f.input :price %>
          <%= f.input :start_date %>
          <%= f.input :billing_frequency, :collection => %w[Weekly Monthly Quarterly Annually 2yr 3yr] %> %>
          <%= f.button :submit, class: "btn add-sub-btn" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/subscriptions/show.html.erb
<div class="text-center align-middle">
  <h1><%= @subscription.title %></h1>
  <p><%= @subscription.price %></p>
  <img src="https://logo.clearbit.com/<%= @subscription.title.split(' ').first.downcase %>.com" class="show-logo">
  <br>
  <br>
  <% if @subscription.title.downcase == 'audible' %>
  <%= render 'audible' %>
  <% end %>

</div>